// Code generated by MockGen. DO NOT EDIT.
// Source: main.go

// Package mock_main is a generated GoMock package.
package mock_main

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockalbumRepoitory is a mock of albumRepoitory interface
type MockalbumRepoitory struct {
	ctrl     *gomock.Controller
	recorder *MockalbumRepoitoryMockRecorder
}

// MockalbumRepoitoryMockRecorder is the mock recorder for MockalbumRepoitory
type MockalbumRepoitoryMockRecorder struct {
	mock *MockalbumRepoitory
}

// NewMockalbumRepoitory creates a new mock instance
func NewMockalbumRepoitory(ctrl *gomock.Controller) *MockalbumRepoitory {
	mock := &MockalbumRepoitory{ctrl: ctrl}
	mock.recorder = &MockalbumRepoitoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockalbumRepoitory) EXPECT() *MockalbumRepoitoryMockRecorder {
	return m.recorder
}

// GetAll mocks base method
func (m *MockalbumRepoitory) GetAll() []album {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]album)
	return ret0
}

// GetAll indicates an expected call of GetAll
func (mr *MockalbumRepoitoryMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockalbumRepoitory)(nil).GetAll))
}

// GetByID mocks base method
func (m *MockalbumRepoitory) GetByID(id string) (album, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(album)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID
func (mr *MockalbumRepoitoryMockRecorder) GetByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockalbumRepoitory)(nil).GetByID), id)
}

// Add mocks base method
func (m *MockalbumRepoitory) Add(arg0 album) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Add", arg0)
}

// Add indicates an expected call of Add
func (mr *MockalbumRepoitoryMockRecorder) Add(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockalbumRepoitory)(nil).Add), arg0)
}
